import json
import random
from datetime import datetime, timedelta

# Kategorilere göre Türkçe ürünler (Trendyol/Amazon tarzı)
products_by_category = {
    1: [  # Elektronik
        ("Apple iPhone 15 Pro Max 256GB", "Apple'ın en güçlü işlemcisi A17 Pro ile donatılmış, titanyum tasarımlı premium akıllı telefon. 48MP ana kamera, 5x optik zoom ve USB-C bağlantı."),
        ("Samsung Galaxy S24 Ultra 512GB", "Snapdragon 8 Gen 3 işlemci, 200MP kamera, S Pen desteği ve yapay zeka özellikleriyle Samsung'un amiral gemisi."),
        ("MacBook Air M3 15 inç", "Apple M3 çip, 15.3 inç Liquid Retina ekran, 18 saat pil ömrü. Sessiz fansız tasarım ile ultra taşınabilir laptop."),
        ("Sony WH-1000XM5 Kablosuz Kulaklık", "Endüstri lideri gürültü engelleme teknolojisi, 30 saat pil ömrü, çok noktalı bağlantı. Hi-Res Audio sertifikalı."),
        ("Apple iPad Pro 12.9 M2 Çip", "M2 çip gücü, ProMotion XDR ekran, LiDAR tarayıcı. Yaratıcı profesyoneller için en güçlü tablet."),
        ("LG OLED65C3 65 inç 4K Smart TV", "OLED evo teknolojisi, α9 AI işlemci, Dolby Vision IQ ve Atmos. Sinema deneyimini evinize taşıyın."),
        ("Apple AirPods Pro 2. Nesil", "Adaptif ses, kişiselleştirilmiş uzamsal ses, USB-C şarj kutusu. Aktif gürültü engelleme ile kristal netliğinde ses."),
        ("PlayStation 5 Digital Edition", "Işın izleme teknolojisi, 4K 120fps oyun desteği, DualSense kablosuz kumanda. Yeni nesil oyun deneyimi."),
        ("DJI Mini 4 Pro Drone", "4K/60fps HDR video, 48MP fotoğraf, 34 dakika uçuş süresi. Engel algılama sensörleri ile güvenli uçuş."),
        ("Canon EOS R6 Mark II Body", "24.2MP full-frame sensör, 40fps seri çekim, 4K 60p video. Profesyonel fotoğrafçılar için aynasız kamera."),
        ("Nintendo Switch OLED Model", "7 inç OLED ekran, 64GB dahili hafıza, geliştirilmiş ses. Evde ve yolda oyun keyfi."),
        ("Dyson V15 Detect Absolute", "Lazer toz algılama, 60 dakika çalışma süresi, LCD ekran. En güçlü kablosuz süpürge teknolojisi."),
        ("Apple Watch Ultra 2", "49mm titanyum kasa, 36 saat pil ömrü, su geçirmez 100m. Macera ve spor tutkunları için tasarlandı."),
        ("Bose SoundLink Max Bluetooth Hoparlör", "Stereo pairing özelliği, 20 saat pil, IP67 su geçirmez. Güçlü bas ve kristal netliğinde ses."),
        ("Logitech MX Master 3S Mouse", "8000 DPI sensör, sessiz tıklama, MagSpeed kaydırma tekerleği. Profesyoneller için ergonomik tasarım."),
        ("ASUS ROG Strix G16 Gaming Laptop", "Intel Core i9-13980HX, RTX 4070, 16GB RAM, 1TB SSD. ROG Nebula ekran ile üst düzey oyun performansı."),
        ("GoPro HERO12 Black", "5.3K video, HyperSmooth 6.0 stabilizasyon, 177° görüş açısı. Ekstrem sporlar için tasarlandı."),
        ("Xiaomi Robot Vacuum S12", "4000Pa emme gücü, LDS lazer navigasyon, akıllı ev entegrasyonu. Otomatik çöp boşaltma istasyonu dahil."),
        ("Razer BlackWidow V4 Pro Klavye", "Razer Green mekanik switch, Chroma RGB, manyetik bilek desteği. Oyuncular için profesyonel klavye."),
        ("Anker PowerCore 26800mAh", "3 USB çıkış portu, 18W hızlı şarj, uçak kabini onaylı. Tüm cihazlarınızı şarj edin.")
    ],
    2: [  # Moda
        ("Nike Air Max 270 Erkek Spor Ayakkabı", "Air Max birim ile maksimum yastıklama, mesh üst kısım ile nefes alabilirlik. Günlük kullanım için ideal."),
        ("Adidas Ultraboost 23 Koşu Ayakkabısı", "Boost orta taban teknolojisi, Primeknit üst, Continental kauçuk taban. Koşucular için enerji geri dönüşü."),
        ("Zara Oversize Blazer Ceket Kadın", "Premium yün karışımlı kumaş, astarlı, çift düğmeli. Ofis ve günlük kombinlere şıklık katar."),
        ("Mavi Jeans Marcus Slim Fit Erkek", "Esnek denim kumaş, slim fit kesim, klasik beş cep tasarım. Rahat ve şık günlük pantolon."),
        ("Tommy Hilfiger Polo Yaka T-Shirt", "%100 pamuk pique kumaş, klasik fit, işlemeli logo. Zamansız Amerikan tarzı."),
        ("Ray-Ban Aviator Classic Güneş Gözlüğü", "Orijinal pilot tasarım, cam lens, altın metal çerçeve. 1937'den beri ikonik stil."),
        ("Michael Kors Jet Set Kadın Çanta", "Saffiano deri, fermuar kapatma, iç cep bölmeleri. Şık ve fonksiyonel omuz çantası."),
        ("Levi's 501 Original Erkek Kot Pantolon", "Düğmeli kopça, düz paça, %100 pamuk denim. 1873'ten beri değişmeyen orijinal kesim."),
        ("Converse Chuck Taylor All Star", "Kanvas üst, kauçuk taban, yıldız logosu. Efsanevi sneaker tasarımı."),
        ("Calvin Klein Erkek Boxer 3'lü Paket", "Pamuk stretch kumaş, esnek bel bandı, logo detayı. Günlük konfor için tasarlandı."),
        ("Lacoste Classic Fit Polo", "Petit pique pamuk, timsah logosu, nervürlü yaka. Fransa'dan orijinal polo gömlek."),
        ("New Balance 574 Unisex Spor Ayakkabı", "ENCAP yastıklama, süet ve mesh kombinasyonu. Retro tasarım, modern konfor."),
        ("Puma RS-X3 Erkek Sneaker", "Running System teknolojisi, kalın taban, retro tasarım. Günlük şık kombinler için."),
        ("Vakko Erkek Deri Cüzdan", "Hakiki deri, RFID koruma, 8 kart bölmesi. El işçiliği ile üretilmiş premium aksesuar."),
        ("Koton Kadın Trençkot", "Su itici kumaş, kemer detaylı, çift sıra düğme. Klasik İngiliz tarzı."),
        ("Timberland 6 Inch Premium Bot", "Nubuk deri, su geçirmez, çelik burunluk. Dayanıklılık ve stil bir arada."),
        ("Swatch Originals Unisex Saat", "İsviçre yapımı, quartz mekanizma, silikon kayış. Renkli ve eğlenceli tasarımlar."),
        ("Guess Kadın Kol Saati Rose Gold", "Paslanmaz çelik kasa, mineral cam, su geçirmez 30m. Zarif ve feminen tasarım."),
        ("Diesel DZ1657 Erkek Kol Saati", "Büyük kadran, deri kayış, mineral cam. Cesur ve maskülen tasarım."),
        ("Ralph Lauren Polo Erkek Parfüm 125ml", "Odunsu aromatik koku, deri ve tütün notaları. Sofistike erkek parfümü.")
    ],
    3: [  # Ev & Yaşam
        ("IKEA MALM Çift Kişilik Yatak Karyola", "160x200 cm, beyaz renk, lata zeminli. Minimalist İskandinav tasarımı."),
        ("Karaca Hatır Türk Kahve Makinesi", "5 kişilik kapasite, otomatik pişirme, bol köpüklü. Türk kahvesi keyfi."),
        ("Madame Coco 6 Parça Yatak Örtüsü Seti", "Jakarlı kumaş, çift kişilik, yastık kılıfları dahil. Şık yatak odası dekorasyonu."),
        ("English Home Bambu Havlu 4'lü Set", "%100 bambu elyaf, antibakteriyel, ekstra emici. Yumuşacık dokunuş."),
        ("TAC Dijital Baskılı Pike Takımı", "Çift kişilik, %100 pamuk, yaz-kış kullanım. Modern desenler."),
        ("Korkmaz Granit Tencere Seti 7 Parça", "Granit kaplama, indüksiyona uygun, PFOA free. Sağlıklı pişirme."),
        ("Emsan Sofram Gold Çeyiz Seti 84 Parça", "Paslanmaz çelik, altın detay, 12 kişilik. Özel günler için."),
        ("Bernardo Premium Kahve Fincan Seti", "6 kişilik, porselen, gold detay. Şık sunum için."),
        ("Tefal Ingenio 13 Parça Tencere Set", "Çıkarılabilir sap, bulaşık makinesi uyumlu, Titanium kaplama. Pratik mutfak."),
        ("Philips Airfryer XXL Premium", "7.3L kapasite, yağsız kızartma, dijital ekran. Sağlıklı pişirme teknolojisi."),
        ("Bosch Serie 6 Bulaşık Makinesi", "13 kişilik, HomeConnect, EcoSilence Drive. Sessiz ve verimli."),
        ("Arçelik No Frost Buzdolabı 540L", "Çift kapılı, sebzelik zone, ion guard teknolojisi. A++ enerji sınıfı."),
        ("Dyson Pure Cool TP07 Hava Temizleyici", "HEPA H13 filtre, 360° hava dolaşımı, uygulama kontrolü. Temiz ve serin hava."),
        ("iRobot Roomba i7+ Robot Süpürge", "Otomatik çöp boşaltma, akıllı haritalama, Alexa uyumlu. Eller serbest temizlik."),
        ("Nespresso Vertuo Next Kahve Makinesi", "Sentrifüj teknolojisi, 5 fincan boyutu, WiFi bağlantı. Barista usulü kahve."),
        ("KitchenAid Artisan Stand Mikser", "4.8L paslanmaz çelik kase, 10 hız, 300W motor. Profesyonel mutfak asistanı."),
        ("Braun MultiQuick 9 El Blenderi", "1200W motor, akıllı hız kontrolü, 6 parça aksesuar. Çok yönlü mutfak robotu."),
        ("Siemens iQ500 Çamaşır Makinesi", "10 kg, 1400 devir, i-Dos otomatik dozaj. Akıllı yıkama programları."),
        ("Vestel 55 inç 4K Google TV", "VA LED panel, Dolby Vision, yerleşik Chromecast. Akıllı televizyon keyfi."),
        ("Electrolux Pure i9.2 Robot Süpürge", "3D görüntüleme, ClimbForce teknolojisi, 120 dakika çalışma. Her köşeye ulaşır.")
    ],
    4: [  # Spor
        ("Nike Dri-FIT Erkek Antrenman Tişört", "Ter emici kumaş teknolojisi, hafif ve nefes alabilir. Yoğun antrenmanlar için."),
        ("Adidas Erkek Eşofman Takımı", "Trikot kumaş, elastik bel, fermuar cepler. Spor ve günlük kullanım."),
        ("Under Armour HeatGear Şort", "Dört yönlü stretch, anti-odor teknolojisi. Maksimum hareket özgürlüğü."),
        ("Puma Kadın Tayt Full-Length", "Yüksek bel, squat-proof kumaş, cep detayı. Fitness ve yoga için."),
        ("Reebok Nano X3 CrossFit Ayakkabı", "Floatride Energy Foam, esnek üst. CrossFit ve ağırlık antrenmanı için."),
        ("Decathlon Btwin 520 Şehir Bisikleti", "21 vites, alüminyum kadro, disk fren. Şehir içi ulaşım için ideal."),
        ("Wilson Pro Staff 97 Tenis Raketi", "315 gram, 97 sq.in. kafa boyutu, Countervail teknolojisi. İleri seviye oyuncular için."),
        ("Speedo Fastskin Yarış Mayosu", "FINA onaylı, hidrodinamik tasarım. Rekabetçi yüzücüler için."),
        ("Arena Swedix Yüzücü Gözlüğü", "Buğu önleyici cam, ayarlanabilir burun köprüsü. Havuz ve açık su için."),
        ("Everlast Pro Style Boks Eldiveni", "Sentetik deri, çift kayış, yoğunluk köpük. Boks antrenmanları için."),
        ("Venum Challenger MMA Eldiveni", "Skintex deri, açık parmak tasarım. Karma dövüş sanatları için."),
        ("Hummel Erkek Futbol Forması", "Nefes alabilir polyester, terletmez teknoloji. Futbol maçları için."),
        ("Molten GG7X Basketbol Topu", "FIBA onaylı, composite deri, iç mekan kullanım. Profesyonel maç topu."),
        ("Mikasa V200W Voleybol Topu", "FIVB onaylı, 18 panel tasarım. Resmi maç topu standartları."),
        ("Head Extreme MP Tenis Raketi", "300 gram, spin odaklı tasarım. Agresif oyuncular için."),
        ("Yonex Astrox 88D Badminton Raketi", "Rotational Generator System, karbon grafit. Profesyonel seviye raket."),
        ("Rossignol Experience 80 Kayak Takımı", "All-mountain kayak, 160cm, bağlama dahil. Orta-ileri seviye kayakçılar için."),
        ("Garmin Forerunner 965 GPS Saat", "AMOLED ekran, 23 gün pil, koşu dinamikleri. Profesyonel koşucular için."),
        ("Theragun Elite Masaj Tabancası", "5 hız, 5 ataşman, QuietForce teknolojisi. Kas gevşetme ve toparlanma."),
        ("TRX Pro4 Sistem Askı Antrenman Seti", "Ayarlanabilir askılar, kapı aparatı dahil. Tüm vücut fonksiyonel antrenman.")
    ],
    5: [  # Kozmetik
        ("L'Oreal Paris Revitalift Cilt Bakım Seti", "Hyaluronik asit serum, göz kremi, nemlendirici. Anti-aging bakım rutini."),
        ("Estée Lauder Advanced Night Repair Serum", "30ml, patentli gece onarım teknolojisi. Cilt yenileme ve aydınlatma."),
        ("MAC Studio Fix Powder Foundation", "15 gram, mat bitirme, orta-tam kapatıcılık. Profesyonel makyaj bazı."),
        ("Maybelline Lash Sensational Maskara", "Yelpaze kirpik etkisi, 7 fırça tüyü. Dolgun ve ayrık kirpikler."),
        ("NYX Professional Makeup Warm Neutrals Palet", "16 renk, mat ve ışıltılı tonlar. Günlük ve gece makyajı için."),
        ("Clinique Moisture Surge 72H Nemlendirici", "Aloe vera ve hyaluronik asit. 72 saat nem tutma özelliği."),
        ("Lancôme La Vie Est Belle Parfüm 75ml", "Iris, jasmine ve praline notaları. Feminin ve zarif kadın parfümü."),
        ("Dior Lip Glow Oil Dudak Yağı", "Kiraz yağı, doğal renk artırıcı. Nemlendirici dudak bakımı."),
        ("Chanel No.5 Eau de Parfum 100ml", "Zamansız klasik, aldehit ve çiçeksi notalar. İkonik parfüm."),
        ("Gucci Bloom Eau de Parfum 100ml", "Jasmine, tuberose ve rangoon çiçeği. Çiçeksi feminen koku."),
        ("Versace Eros Erkek Parfüm 100ml", "Nane, yeşil elma ve vanilya. Seksi ve çekici erkek parfümü."),
        ("Calvin Klein One EDT 200ml", "Unisex, narenciye ve musk. Temiz ve ferah günlük koku."),
        ("Hugo Boss Bottled EDT 100ml", "Elma, tarçın ve sandal ağacı. Klasik erkek parfümü."),
        ("Dove Beauty Cream Bar Sabun 4'lü", "1/4 nemlendirici krem, hassas ciltler için. Besleyici temizlik."),
        ("Pantene Pro-V Onarıcı Şampuan 500ml", "Pro-vitamin B5 formülü, yıpranmış saçlar için. Kök uçtan uca onarım."),
        ("Head & Shoulders Kepek Karşıtı Şampuan", "ZPT teknolojisi, kepek giderici. Temiz ve sağlıklı saç derisi."),
        ("Garnier C Vitamini Aydınlatıcı Serum", "Niacinamide ve salisilik asit. Leke karşıtı, aydınlatıcı formül."),
        ("The Ordinary Niacinamide 10% + Zinc 1%", "30ml, gözenek sıkılaştırıcı, cilt tonu düzenleyici. Vegan formül."),
        ("La Roche-Posay Effaclar Duo+", "Niacinamide ve LHA, akne karşıtı bakım. Dermatoloji uzmanı onaylı."),
        ("Nivea Soft Nemlendirici Krem 300ml", "E vitamini ve jojoba yağı. Hızlı emilen tüm cilt tiplerine uygun.")
    ],
    6: [  # Kitap
        ("Sapiens: İnsan Türünün Kısa Tarihi - Yuval N. Harari", "İnsanlık tarihinin 70.000 yıllık yolculuğu. Dünya çapında 20 milyondan fazla satış."),
        ("Atomic Habits - James Clear", "Alışkanlık bilimi ve kişisel gelişim rehberi. Küçük değişiklikler, büyük sonuçlar."),
        ("1984 - George Orwell", "Distopik edebiyatın başyapıtı. Gözetim toplumu ve bireysel özgürlük üzerine."),
        ("Suç ve Ceza - Fyodor Dostoyevski", "Rus edebiyatının klasiği. Ahlak, suç ve psikolojik derinlik."),
        ("Kürk Mantolu Madonna - Sabahattin Ali", "Türk edebiyatının en çok okunan romanlarından. Aşk ve özlem hikayesi."),
        ("Tutunamayanlar - Oğuz Atay", "Postmodern Türk edebiyatının başyapıtı. Toplumsal yabancılaşma teması."),
        ("Simyacı - Paulo Coelho", "Kişisel efsane arayışı. 80'den fazla dile çevrilmiş dünya klasiği."),
        ("Harry Potter ve Felsefe Taşı - J.K. Rowling", "Büyülü serinin ilk kitabı. Her yaştan okur için fantastik macera."),
        ("Yüzüklerin Efendisi - J.R.R. Tolkien", "Fantastik edebiyatın temel taşı. Orta Dünya'da epik macera."),
        ("Hobbit - J.R.R. Tolkien", "Bilbo Baggins'in beklenmedik yolculuğu. Yüzüklerin Efendisi öncesi hikaye."),
        ("Da Vinci Şifresi - Dan Brown", "Sanat tarihi ve gizem dolu gerilim romanı. Dünya çapında fenomen."),
        ("Sherlock Holmes Tüm Hikayeler - Arthur Conan Doyle", "Dedektif edebiyatının başyapıtları. 4 roman ve 56 kısa hikaye."),
        ("Agatha Christie - Doğu Ekspresinde Cinayet", "Hercule Poirot'nun en ünlü davası. Klasik polisiye romanı."),
        ("Stephen King - IT", "Korku türünün başyapıtı. Pennywise'ın dehşet saçan hikayesi."),
        ("Dune - Frank Herbert", "Bilim kurgunun en büyük destanlarından. Çöl gezegeni Arrakis'te geçen epik hikaye."),
        ("Fahrenheit 451 - Ray Bradbury", "Kitapların yasaklandığı distopik dünya. Edebiyat ve özgürlük üzerine."),
        ("Cesur Yeni Dünya - Aldous Huxley", "Teknolojik distopya klasiği. Mutluluğun kontrolü ve bireysellik."),
        ("Hayvan Çiftliği - George Orwell", "Politik alegori ve toplumsal eleştiri. Tüm zamanların klasiği."),
        ("Otostopçunun Galaksi Rehberi - Douglas Adams", "Bilim kurgu ve mizahın mükemmel karışımı. Galaktik macera."),
        ("Nutuk - Mustafa Kemal Atatürk", "Türk Kurtuluş Savaşı ve Cumhuriyet'in kuruluşu. Tarihi belge.")
    ],
    7: [  # Oyuncak
        ("LEGO Technic Bugatti Chiron 42083", "3599 parça, 1:8 ölçek, gerçekçi detaylar. Koleksiyonluk model set."),
        ("Barbie Dreamhouse 2024", "3 katlı, 10+ odalı, ışık ve ses efektleri. Rüya evi deneyimi."),
        ("Hot Wheels Ultimate Pist Seti", "Çoklu parkur, motorlu fırlatıcı, 5 araç dahil. Aksiyon dolu yarış."),
        ("Nerf Elite 2.0 Shockwave RD-15", "15 dart kapasiteli, hızlı ateş modu. Stratejik savaş oyunları için."),
        ("Play-Doh Mega Kuaför Seti", "15 kutu oyun hamuru, saç kesme aksesuarları. Yaratıcılık için."),
        ("Monopoly Dijital Bankacılık Versiyon", "Elektronik bankacılık ünitesi, klasik oyun. Aile oyun gecesi için."),
        ("UNO Ultimate Marvel", "112 kart, özel Marvel karakterleri. Süper kahraman temalı kart oyunu."),
        ("Rubik Küp Orijinal 3x3", "Orijinal Macar tasarımı, döner mekanizma. Beyin geliştirici zeka oyunu."),
        ("Ravensburger 1000 Parça Puzzle", "Yüksek kalite baskı, çeşitli temalar. Yetişkinler için puzzle keyfi."),
        ("Fisher-Price Eğitici Telefon", "Işıklı tuşlar, müzikler, sesler. 6-36 ay bebekler için."),
        ("Little Tikes Cozy Coupe", "Pedalsız ilk araba, kornalı, bacakla sürme. 18 ay - 5 yaş."),
        ("Hasbro Transformers Optimus Prime", "Dönüşebilir aksiyon figürü, 30cm. Koleksiyonluk karakter."),
        ("Mattel Jurassic World T-Rex Oyuncağı", "Gerçekçi sesler, hareket, 54cm. Dinozor meraklıları için."),
        ("Playmobil Polis Merkezi Seti", "120+ parça, 4 figür, araç dahil. Detaylı rol yapma oyunu."),
        ("LEGO City Uzay İstasyonu 60349", "500 parça, astronot figürleri. NASA temalı uzay macerası."),
        ("Crayola Inspiration Art Case", "140 parça sanat seti, boya kalemleri, keçeli kalemler. Yaratıcı çocuklar için."),
        ("Melissa & Doug Ahşap Mutfak Seti", "Doğal ahşap, yıkanabilir, güvenli boyalar. Montessori eğitim oyuncağı."),
        ("VTech KidiZoom Smartwatch DX3", "Çocuk akıllı saati, kamera, oyunlar. 4-9 yaş için teknoloji deneyimi."),
        ("Baby Alive Gerçek Bebek", "Yemek yiyen, bez değiştiren, konuşan bebek. Bakım oyunu için."),
        ("Schleich Çiftlik Hayvanları Seti", "El boyaması detaylı figürler. Eğitici hayvan koleksiyonu.")
    ],
    8: [  # Gıda
        ("Ülker Çikolatalı Gofret 5'li Paket", "Sütlü çikolata kaplı, gevrek gofret katları. Klasik Türk atıştırmalığı."),
        ("Eti Browni İntense Kek 4'lü", "Yoğun çikolata, yumuşacık doku. Şeker ihtiyacı için ideal."),
        ("Lay's Klasik Patates Cipsi Aile Boy", "Doğal patates, tuz. Parti ve film gecesi için."),
        ("Doritos Nacho Peynir Cips", "Meksika esintili peynir aroması. Sos ile mükemmel ikili."),
        ("Coca-Cola Zero Sugar 6x1L", "Şekersiz, sıfır kalori, orijinal tat. Aile boy paket."),
        ("Nescafe Gold 200g Kavanoz", "Arabica çekirdek, yumuşak tat. Premium hazır kahve."),
        ("Lipton Yellow Label Demlik Poşet Çay 100'lü", "Premium Ceylon çayı. Türk çay geleneği için."),
        ("Algida Magnum Badem Dondurma 4'lü", "Belçika çikolatası, badem parçacıkları. Lüks dondurma keyfi."),
        ("Nutella Kakaolu Fındık Kreması 630g", "İtalyan orijinal tarif, fındık ve kakao. Kahvaltı klasiği."),
        ("Philadelphia Orjinal Krem Peynir 300g", "Yumuşak kıvam, doğal malzemeler. Kahvaltı ve yemek için."),
        ("Pınar Tam Yağlı Süt 6x1L", "Günlük taze süt, kalsiyum deposu. Aile boy ekonomik paket."),
        ("Sütaş Probiyotik Yoğurt 1000g", "Probiyotik kültür, doğal ve sağlıklı. Sindirim dostu."),
        ("Torku Banada Çikolatalı Bar 5'li", "Çikolata kaplamalı, bisküvi kıtırlığı. Enerjik atıştırmalık."),
        ("Tadım Karışık Kuruyemiş 250g", "Fındık, badem, antep fıstığı, ceviz. Sağlıklı snack."),
        ("Çaykur Tiryaki Çay 1000g", "Doğu Karadeniz çayı, geleneksel tat. Türk çay kültürü."),
        ("Jacobs Monarch Gold 200g", "Freeze-dried teknolojisi, zengin aroma. Kaliteli hazır kahve."),
        ("Monster Energy Drink 6x500ml", "Kafein, taurin, B vitaminleri. Enerji ihtiyacı için."),
        ("Red Bull Energy Drink 4x250ml", "Dünyaca ünlü enerji içeceği. Konsantrasyon ve performans için."),
        ("Ülker İkram Sandviç Bisküvi 3'lü", "Çikolata kremalı, gevrek bisküvi. Çay saati klasiği."),
        ("ETİ Çikolata Keyfi 6'lı Paket", "Sütlü, bitter, fındıklı çeşitler. Çikolata tutkunları için.")
    ],
    9: [  # Otomotiv
        ("Michelin CrossClimate 2 205/55R16", "Tüm hava koşulları lastiği, uzun ömür. 4 mevsim güvenli sürüş."),
        ("Bosch S5 Akü 72Ah", "AGM teknolojisi, Start-Stop uyumlu. Güçlü ve güvenilir."),
        ("Castrol EDGE 5W-30 Motor Yağı 4L", "Fluid Titanium Technology, tam sentetik. Motor koruma ve performans."),
        ("Shell Helix HX8 5W-40 Motor Yağı", "Aktif temizleme teknolojisi, sentetik. Uzun motor ömrü."),
        ("Philips H7 LED Ampul Seti", "200% daha fazla ışık, 6500K beyaz. Gece sürüşü güvenliği."),
        ("Pioneer AVH-Z9250BT Multimedya Ünitesi", "9 inç ekran, Apple CarPlay, Android Auto. Akıllı araç sistemi."),
        ("JBL Club 6520 Hoparlör Seti", "150W, 2-way, premium ses. Araç içi müzik keyfi."),
        ("Kenwood KDC-BT530U Teyp", "Bluetooth, USB, Spotify control. Temiz ve güçlü ses."),
        ("3M Tint Film Pencere Filmi", "UV koruma, ısı reddi, %35 geçirgenlik. Profesyonel uygulama."),
        ("Meguiar's Gold Class Wax", "Carnauba wax, derin parlaklık. Show car finish."),
        ("Armor All Araç İçi Temizleyici Set", "Torpido, koltuk, cam temizliği. Komple bakım seti."),
        ("Turtle Wax Cilalı Şampuan 5L", "Wax içerikli, pH nötr, güvenli yıkama. Parlaklık veren formül."),
        ("Chemical Guys Leather Cleaner", "Deri temizleme ve bakım. Kokpit detaylandırma."),
        ("WeatherTech Özel Ölçü Paspas Seti", "3D lazer ölçüm, su geçirmez. Marka uyumlu tasarım."),
        ("Thule Motion XT XL Tavan Çantası", "500L kapasite, aerodinamik, kilitli. Yolculuk bagajı."),
        ("Yakima Tavan Barı Sistemi", "Aerodynamik profil, sessiz sürüş. Kayak ve bisiklet taşıma."),
        ("Osram Night Breaker H4 Ampul", "+150% daha fazla ışık, 3900K. Gelişmiş gece görüşü."),
        ("Bosch Silecek Takımı Aerotwin", "Aerodinamik tasarım, sessiz çalışma. Net görüş."),
        ("Goodyear Excellence 225/45R17", "Premium yaz lastiği, düşük yuvarlanma direnci. Konfor ve ekonomi."),
        ("Varta Blue Dynamic Akü 60Ah", "PowerFrame teknolojisi, güçlü start. Güvenilir enerji kaynağı.")
    ],
    10: [  # Bahçe
        ("Weber Genesis II E-310 Gazlı Mangal", "3 brülör, 669 sq.in. pişirme alanı. Profesyonel barbekü deneyimi."),
        ("Gardena Comfort Hortum 30m Set", "Anti-kink teknolojisi, 25 yıl garanti. Dayanıklı bahçe hortumu."),
        ("Bosch UniversalGrassCut 18 Tırpan", "35cm kesim çapı, akülü. Sessiz ve çevre dostu."),
        ("Fiskars PowerGear X Budama Makası", "Dişli teknolojisi, 3x daha az kuvvet. Profesyonel bahçe aracı."),
        ("Kärcher K5 Premium Basınçlı Yıkama", "2100W, 145 bar, su soğutmalı motor. Güçlü temizlik."),
        ("Makita DUB362Z Akülü Yaprak Üfleyici", "36V, 52 m/s hava hızı. Bahçe temizliği için."),
        ("Black+Decker 40cm Elektrikli Çim Biçme", "1800W motor, 50L çim toplama. Orta boy bahçeler için."),
        ("Husqvarna Automower 305 Robot Çim Biçme", "Otomatik çim biçme, GPS navigasyon. Akıllı bahçe bakımı."),
        ("Stihl MS 180 Motorlu Testere", "1.5 kW, 35cm kılavuz. Hobi ve yarı profesyonel kullanım."),
        ("Bahçe Mobilya Rattan Oturma Grubu", "4 kişilik, su geçirmez minder. Şık dış mekan dekorasyonu."),
        ("Weber Smokey Mountain Defüme Mangal", "Uzun pişirme, gerçek füme tadı. BBQ ustaları için."),
        ("Claber Aqua Magic Otomatik Sulama", "Programlanabilir, 20 çıkış. Tatil sulama sistemi."),
        ("Gardena AquaContour Sprink Sistemi", "350 m2 kapsama, ayarlanabilir. Çim sulama çözümü."),
        ("Keter Bahçe Alet Dolabı", "Su geçirmez, kilitli, raflar. Düzenli bahçe deposu."),
        ("Stihl BR 200 Sırt Tipi Üfleyici", "Benzinli, 27.2cc motor. Büyük alanlar için güçlü."),
        ("Fiskars Xact Bahçe Küreği", "Ergonomik sap, paslanmaz çelik. Toprak işleme için."),
        ("Çim Tohumu Karışımı 10 Kg", "4 mevsim dayanıklı, çabuk yeşeren. Güzel çim halısı."),
        ("Organik Bahçe Gübresi 25 Kg", "Doğal içerik, tüm bitkiler için. Verimli hasat."),
        ("LED Güneş Enerjili Bahçe Lambası 6'lı", "Otomatik açılma, 8 saat aydınlatma. Dekoratif ışıklandırma."),
        ("Bahçe Salıncağı 3 Kişilik Tente", "Hava koşuluna dayanıklı, rahat minder. Ailece keyif.")
    ]
}

products = []
product_id = 1

for category_id, product_list in products_by_category.items():
    for name, description in product_list:
        days_ago = random.randint(30, 365)
        created = datetime.now() - timedelta(days=days_ago)
        
        products.append({
            "id": product_id,
            "name": name,
            "description": description,
            "price": random.randint(50, 15000),
            "currency": "TRY",
            "sku": product_id,
            "isActive": random.random() > 0.15,
            "categoryId": category_id,
            "createdAt": created.strftime("%Y-%m-%dT%H:%M:%SZ"),
            "updatedAt": created.strftime("%Y-%m-%dT%H:%M:%SZ")
        })
        product_id += 1

with open("seed-data/products.json", "w", encoding="utf-8") as f:
    json.dump(products, f, ensure_ascii=False, indent=2)

print(f"✅ {len(products)} Türkçe ürün oluşturuldu!")
print(f"📁 Dosya: seed-data/products.json")
