CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE TABLE "Categories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(255) NOT NULL,
        "Description" character varying(1000) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE TABLE "Roles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(50) NOT NULL,
        "Description" character varying(500) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE TABLE "Products" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(255) NOT NULL,
        "Description" character varying(2000) NOT NULL,
        "Price" numeric(18,2) NOT NULL,
        "Currency" character varying(3) NOT NULL,
        "SKU" character varying(100) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CategoryId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Email" character varying(255) NOT NULL,
        "PasswordHash" character varying(500) NOT NULL,
        "FirstName" character varying(100) NOT NULL,
        "LastName" character varying(100) NOT NULL,
        "RoleId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE TABLE "Inventories" (
        "ProductId" integer NOT NULL,
        "QuantityAvailable" integer NOT NULL,
        "QuantityReserved" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Inventories" PRIMARY KEY ("ProductId"),
        CONSTRAINT "FK_Inventories_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE TABLE "Carts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Carts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Carts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE TABLE "InventoryMovements" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" integer NOT NULL,
        "UserId" integer NOT NULL,
        "Delta" integer NOT NULL,
        "Reason" character varying(100) NOT NULL,
        "Notes" character varying(1000) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_InventoryMovements" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_InventoryMovements_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_InventoryMovements_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE TABLE "Orders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderNumber" character varying(50) NOT NULL,
        "UserId" integer NOT NULL,
        "Status" integer NOT NULL,
        "TotalAmount" numeric(18,2) NOT NULL,
        "Currency" character varying(3) NOT NULL,
        "ShippingAddress" character varying(1000) NOT NULL,
        "Notes" text NOT NULL,
        "CancelledAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Orders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE TABLE "CartItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CartId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "PriceSnapshot" numeric(18,2) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CartItems_Carts_CartId" FOREIGN KEY ("CartId") REFERENCES "Carts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CartItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE TABLE "OrderItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "PriceSnapshot" numeric(18,2) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE TABLE "Payments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "Currency" character varying(3) NOT NULL,
        "Status" integer NOT NULL,
        "PaymentMethod" character varying(50) NOT NULL,
        "PaymentProviderId" text,
        "IdempotencyKey" character varying(255) NOT NULL,
        "ErrorMessage" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Payments_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_CartItems_CartId_ProductId" ON "CartItems" ("CartId", "ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE INDEX "IX_CartItems_ProductId" ON "CartItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Carts_UserId" ON "Carts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Categories_Name" ON "Categories" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE INDEX "IX_InventoryMovements_CreatedAt" ON "InventoryMovements" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE INDEX "IX_InventoryMovements_ProductId" ON "InventoryMovements" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE INDEX "IX_InventoryMovements_UserId" ON "InventoryMovements" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE INDEX "IX_OrderItems_ProductId" ON "OrderItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE INDEX "IX_Orders_CreatedAt" ON "Orders" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Orders_OrderNumber" ON "Orders" ("OrderNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE INDEX "IX_Orders_Status" ON "Orders" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE INDEX "IX_Orders_UserId" ON "Orders" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Payments_IdempotencyKey" ON "Payments" ("IdempotencyKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Payments_OrderId" ON "Payments" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE INDEX "IX_Products_IsActive" ON "Products" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE INDEX "IX_Products_Price" ON "Products" ("Price");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Products_SKU" ON "Products" ("SKU");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Roles_Name" ON "Roles" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218181843_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251218181843_InitialCreate', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221111908_AddShippingAddress') THEN
    CREATE TABLE "ShippingAddresses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Title" text NOT NULL,
        "FullName" text NOT NULL,
        "Phone" text NOT NULL,
        "City" text NOT NULL,
        "District" text NOT NULL,
        "AddressLine" text NOT NULL,
        "PostalCode" text,
        "IsDefault" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ShippingAddresses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ShippingAddresses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221111908_AddShippingAddress') THEN
    CREATE INDEX "IX_ShippingAddresses_UserId" ON "ShippingAddresses" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221111908_AddShippingAddress') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251221111908_AddShippingAddress', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221120621_AddKvkkEncryption') THEN
    DROP INDEX "IX_Users_Email";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221120621_AddKvkkEncryption') THEN
    ALTER TABLE "Users" ALTER COLUMN "LastName" TYPE character varying(300);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221120621_AddKvkkEncryption') THEN
    ALTER TABLE "Users" ALTER COLUMN "FirstName" TYPE character varying(300);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221120621_AddKvkkEncryption') THEN
    ALTER TABLE "Users" ALTER COLUMN "Email" TYPE character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221120621_AddKvkkEncryption') THEN
    ALTER TABLE "Users" ADD "EmailHash" character varying(64) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221120621_AddKvkkEncryption') THEN
    ALTER TABLE "ShippingAddresses" ALTER COLUMN "Title" TYPE character varying(300);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221120621_AddKvkkEncryption') THEN
    ALTER TABLE "ShippingAddresses" ALTER COLUMN "PostalCode" TYPE character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221120621_AddKvkkEncryption') THEN
    ALTER TABLE "ShippingAddresses" ALTER COLUMN "Phone" TYPE character varying(300);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221120621_AddKvkkEncryption') THEN
    ALTER TABLE "ShippingAddresses" ALTER COLUMN "FullName" TYPE character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221120621_AddKvkkEncryption') THEN
    ALTER TABLE "ShippingAddresses" ALTER COLUMN "District" TYPE character varying(300);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221120621_AddKvkkEncryption') THEN
    ALTER TABLE "ShippingAddresses" ALTER COLUMN "City" TYPE character varying(300);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221120621_AddKvkkEncryption') THEN
    ALTER TABLE "ShippingAddresses" ALTER COLUMN "AddressLine" TYPE character varying(1000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221120621_AddKvkkEncryption') THEN
    CREATE UNIQUE INDEX "IX_Users_EmailHash" ON "Users" ("EmailHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221120621_AddKvkkEncryption') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251221120621_AddKvkkEncryption', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221132558_AddRefreshToken') THEN
    CREATE TABLE "RefreshTokens" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Token" character varying(200) NOT NULL,
        "JwtId" character varying(100) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsRevoked" boolean NOT NULL,
        "IsUsed" boolean NOT NULL,
        "ReplacedByToken" character varying(200),
        "RevokedReason" character varying(200),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221132558_AddRefreshToken') THEN
    CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221132558_AddRefreshToken') THEN
    CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221132558_AddRefreshToken') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251221132558_AddRefreshToken', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "CartItems" DROP CONSTRAINT "FK_CartItems_Carts_CartId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "CartItems" DROP CONSTRAINT "FK_CartItems_Products_ProductId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Carts" DROP CONSTRAINT "FK_Carts_Users_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Inventories" DROP CONSTRAINT "FK_Inventories_Products_ProductId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "InventoryMovements" DROP CONSTRAINT "FK_InventoryMovements_Products_ProductId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "InventoryMovements" DROP CONSTRAINT "FK_InventoryMovements_Users_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "OrderItems" DROP CONSTRAINT "FK_OrderItems_Orders_OrderId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "OrderItems" DROP CONSTRAINT "FK_OrderItems_Products_ProductId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Orders" DROP CONSTRAINT "FK_Orders_Users_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Payments" DROP CONSTRAINT "FK_Payments_Orders_OrderId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Products" DROP CONSTRAINT "FK_Products_Categories_CategoryId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "RefreshTokens" DROP CONSTRAINT "FK_RefreshTokens_Users_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "ShippingAddresses" DROP CONSTRAINT "FK_ShippingAddresses_Users_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Users" DROP CONSTRAINT "FK_Users_Roles_RoleId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Users" DROP CONSTRAINT "PK_Users";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "ShippingAddresses" DROP CONSTRAINT "PK_ShippingAddresses";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Roles" DROP CONSTRAINT "PK_Roles";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "RefreshTokens" DROP CONSTRAINT "PK_RefreshTokens";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Products" DROP CONSTRAINT "PK_Products";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Payments" DROP CONSTRAINT "PK_Payments";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Orders" DROP CONSTRAINT "PK_Orders";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "OrderItems" DROP CONSTRAINT "PK_OrderItems";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "InventoryMovements" DROP CONSTRAINT "PK_InventoryMovements";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Inventories" DROP CONSTRAINT "PK_Inventories";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Categories" DROP CONSTRAINT "PK_Categories";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Carts" DROP CONSTRAINT "PK_Carts";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "CartItems" DROP CONSTRAINT "PK_CartItems";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Users" RENAME TO "TBL_Users";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "ShippingAddresses" RENAME TO "TBL_ShippingAddresses";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Roles" RENAME TO "TBL_Roles";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "RefreshTokens" RENAME TO "TBL_RefreshTokens";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Products" RENAME TO "TBL_Products";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Payments" RENAME TO "TBL_Payments";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Orders" RENAME TO "TBL_Orders";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "OrderItems" RENAME TO "TBL_OrderItems";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "InventoryMovements" RENAME TO "TBL_InventoryMovements";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Inventories" RENAME TO "TBL_Inventories";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Categories" RENAME TO "TBL_Categories";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "Carts" RENAME TO "TBL_Carts";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "CartItems" RENAME TO "TBL_CartItems";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_Users_RoleId" RENAME TO "IX_TBL_Users_RoleId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_Users_EmailHash" RENAME TO "IX_TBL_Users_EmailHash";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_ShippingAddresses_UserId" RENAME TO "IX_TBL_ShippingAddresses_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_Roles_Name" RENAME TO "IX_TBL_Roles_Name";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_RefreshTokens_UserId" RENAME TO "IX_TBL_RefreshTokens_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_RefreshTokens_Token" RENAME TO "IX_TBL_RefreshTokens_Token";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_Products_SKU" RENAME TO "IX_TBL_Products_SKU";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_Products_Price" RENAME TO "IX_TBL_Products_Price";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_Products_IsActive" RENAME TO "IX_TBL_Products_IsActive";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_Products_CategoryId" RENAME TO "IX_TBL_Products_CategoryId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_Payments_OrderId" RENAME TO "IX_TBL_Payments_OrderId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_Payments_IdempotencyKey" RENAME TO "IX_TBL_Payments_IdempotencyKey";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_Orders_UserId" RENAME TO "IX_TBL_Orders_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_Orders_Status" RENAME TO "IX_TBL_Orders_Status";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_Orders_OrderNumber" RENAME TO "IX_TBL_Orders_OrderNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_Orders_CreatedAt" RENAME TO "IX_TBL_Orders_CreatedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_OrderItems_ProductId" RENAME TO "IX_TBL_OrderItems_ProductId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_OrderItems_OrderId" RENAME TO "IX_TBL_OrderItems_OrderId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_InventoryMovements_UserId" RENAME TO "IX_TBL_InventoryMovements_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_InventoryMovements_ProductId" RENAME TO "IX_TBL_InventoryMovements_ProductId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_InventoryMovements_CreatedAt" RENAME TO "IX_TBL_InventoryMovements_CreatedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_Categories_Name" RENAME TO "IX_TBL_Categories_Name";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_Carts_UserId" RENAME TO "IX_TBL_Carts_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_CartItems_ProductId" RENAME TO "IX_TBL_CartItems_ProductId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER INDEX "IX_CartItems_CartId_ProductId" RENAME TO "IX_TBL_CartItems_CartId_ProductId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_Users" ADD CONSTRAINT "PK_TBL_Users" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_ShippingAddresses" ADD CONSTRAINT "PK_TBL_ShippingAddresses" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_Roles" ADD CONSTRAINT "PK_TBL_Roles" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_RefreshTokens" ADD CONSTRAINT "PK_TBL_RefreshTokens" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_Products" ADD CONSTRAINT "PK_TBL_Products" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_Payments" ADD CONSTRAINT "PK_TBL_Payments" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_Orders" ADD CONSTRAINT "PK_TBL_Orders" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_OrderItems" ADD CONSTRAINT "PK_TBL_OrderItems" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_InventoryMovements" ADD CONSTRAINT "PK_TBL_InventoryMovements" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_Inventories" ADD CONSTRAINT "PK_TBL_Inventories" PRIMARY KEY ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_Categories" ADD CONSTRAINT "PK_TBL_Categories" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_Carts" ADD CONSTRAINT "PK_TBL_Carts" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_CartItems" ADD CONSTRAINT "PK_TBL_CartItems" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_CartItems" ADD CONSTRAINT "FK_TBL_CartItems_TBL_Carts_CartId" FOREIGN KEY ("CartId") REFERENCES "TBL_Carts" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_CartItems" ADD CONSTRAINT "FK_TBL_CartItems_TBL_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "TBL_Products" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_Carts" ADD CONSTRAINT "FK_TBL_Carts_TBL_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "TBL_Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_Inventories" ADD CONSTRAINT "FK_TBL_Inventories_TBL_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "TBL_Products" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_InventoryMovements" ADD CONSTRAINT "FK_TBL_InventoryMovements_TBL_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "TBL_Products" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_InventoryMovements" ADD CONSTRAINT "FK_TBL_InventoryMovements_TBL_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "TBL_Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_OrderItems" ADD CONSTRAINT "FK_TBL_OrderItems_TBL_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "TBL_Orders" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_OrderItems" ADD CONSTRAINT "FK_TBL_OrderItems_TBL_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "TBL_Products" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_Orders" ADD CONSTRAINT "FK_TBL_Orders_TBL_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "TBL_Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_Payments" ADD CONSTRAINT "FK_TBL_Payments_TBL_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "TBL_Orders" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_Products" ADD CONSTRAINT "FK_TBL_Products_TBL_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "TBL_Categories" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_RefreshTokens" ADD CONSTRAINT "FK_TBL_RefreshTokens_TBL_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "TBL_Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_ShippingAddresses" ADD CONSTRAINT "FK_TBL_ShippingAddresses_TBL_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "TBL_Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    ALTER TABLE "TBL_Users" ADD CONSTRAINT "FK_TBL_Users_TBL_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "TBL_Roles" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251221161502_RenameTablesWithTBLPrefix') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251221161502_RenameTablesWithTBLPrefix', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251223080137_AddCouponTable') THEN
    ALTER TABLE "TBL_Orders" ALTER COLUMN "ShippingAddress" TYPE character varying(2000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251223080137_AddCouponTable') THEN
    ALTER TABLE "TBL_Orders" ADD "CouponCode" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251223080137_AddCouponTable') THEN
    ALTER TABLE "TBL_Orders" ADD "CouponId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251223080137_AddCouponTable') THEN
    ALTER TABLE "TBL_Orders" ADD "DiscountAmount" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251223080137_AddCouponTable') THEN
    CREATE TABLE "Coupons" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" text NOT NULL,
        "Type" integer NOT NULL,
        "Value" numeric NOT NULL,
        "MinOrderAmount" numeric,
        "UsageLimit" integer NOT NULL,
        "UsedCount" integer NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        "Description" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Coupons" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251223080137_AddCouponTable') THEN
    CREATE INDEX "IX_TBL_Orders_CouponId" ON "TBL_Orders" ("CouponId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251223080137_AddCouponTable') THEN
    ALTER TABLE "TBL_Orders" ADD CONSTRAINT "FK_TBL_Orders_Coupons_CouponId" FOREIGN KEY ("CouponId") REFERENCES "Coupons" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251223080137_AddCouponTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251223080137_AddCouponTable', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224043334_AddSellerProfile') THEN
    ALTER TABLE "TBL_Products" ADD "SellerId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224043334_AddSellerProfile') THEN
    CREATE TABLE "TBL_SellerProfiles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "BrandName" character varying(200) NOT NULL,
        "BrandDescription" character varying(2000),
        "LogoUrl" character varying(500),
        "IsVerified" boolean NOT NULL DEFAULT FALSE,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_TBL_SellerProfiles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TBL_SellerProfiles_TBL_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "TBL_Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224043334_AddSellerProfile') THEN
    CREATE INDEX "IX_TBL_Products_SellerId" ON "TBL_Products" ("SellerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224043334_AddSellerProfile') THEN
    CREATE INDEX "IX_TBL_SellerProfiles_BrandName" ON "TBL_SellerProfiles" ("BrandName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224043334_AddSellerProfile') THEN
    CREATE UNIQUE INDEX "IX_TBL_SellerProfiles_UserId" ON "TBL_SellerProfiles" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224043334_AddSellerProfile') THEN
    ALTER TABLE "TBL_Products" ADD CONSTRAINT "FK_TBL_Products_TBL_SellerProfiles_SellerId" FOREIGN KEY ("SellerId") REFERENCES "TBL_SellerProfiles" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224043334_AddSellerProfile') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251224043334_AddSellerProfile', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224054158_RenameCouponTableWithTBLPrefix') THEN
    ALTER TABLE "Coupons" RENAME TO "TBL_Coupons";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224054158_RenameCouponTableWithTBLPrefix') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251224054158_RenameCouponTableWithTBLPrefix', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225075956_AddCreditCards') THEN
    CREATE TABLE "TBL_CreditCards" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "CardAlias" character varying(200) NOT NULL,
        "CardHolderName" character varying(500) NOT NULL,
        "CardNumberEncrypted" character varying(500) NOT NULL,
        "Last4Digits" character varying(4) NOT NULL,
        "ExpireYearEncrypted" character varying(200) NOT NULL,
        "ExpireMonthEncrypted" character varying(200) NOT NULL,
        "CvvEncrypted" character varying(200) NOT NULL,
        "IsDefault" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_TBL_CreditCards" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TBL_CreditCards_TBL_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "TBL_Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225075956_AddCreditCards') THEN
    CREATE INDEX "IX_TBL_CreditCards_UserId" ON "TBL_CreditCards" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225075956_AddCreditCards') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251225075956_AddCreditCards', '8.0.11');
    END IF;
END $EF$;
COMMIT;

